# TP1 : Rock-paper-scissors

## Lab session

### Markov Chain simulation

In [2]:
from random import random

import numpy as np
from tkinter import*
import matplotlib.pyplot as plt
import matplotlib
matplotlib.use("TkAgg")
from matplotlib.backends.backend_tkagg import FigureCanvasTkAgg
from matplotlib.figure import Figure

### Question 1 : Create transition matrix "P".

In [3]:
P = np.array([
    [0.8, 0.1, 0.1],
    [0.3, 0.4, 0.3],
    [0.1, 0.1, 0.8]
])

### Question 2 : Create the function "randomPFS(a,b)". Explain your algorithm.

In [4]:
def randomPFS(a,b):
    return np.random.choice([0, 1, 2], p=[a, b, 1 - a - b])

### Question 3 : Create the function "sampleMarkov(P,n)".

In [5]:
def sampleMarkov(P, n):
    states = [0, 1, 2]  # Possible states
    chain = [np.random.choice(states)]  # Initialize with a random state
    for _ in range(1, n):
        current_state = chain[-1]
        next_state = np.random.choice(states, p=P[current_state])
        chain.append(next_state)
    return chain


In [6]:
n = 100
markov_chain = sampleMarkov(P, n)
print("Generated Markov Chain:", markov_chain)

Generated Markov Chain: [np.int64(2), np.int64(2), np.int64(2), np.int64(2), np.int64(2), np.int64(2), np.int64(2), np.int64(2), np.int64(2), np.int64(2), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(2), np.int64(2), np.int64(2), np.int64(2), np.int64(2), np.int64(0), np.int64(0), np.int64(2), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(2), np.int64(2), np.int64(2), np.int64(2), np.int64(2), np.int64(2), np.int64(2), np.int64(2), np.int64(2), np.int64(2), np.int64(2), np.int64(2), np.int64(2), np.int64(2), np.int64(2), np.int64(2), np.int64(2), np.int64(2), np.int64(1), np.int64(0), np.int64(0), np.int64(0), np.int64(2), np.int64(2), np.int64(2), np.int64(2), np.int64(2), np.int64(2), np.int64(2), np.int64(2), np.int64(2), np.int64(0), np.int64(0), np.int64(0), np.int64(1), np.int64(0), np.int64(2), np.int64(2), np.int64(2), np.int64(0), np.int64(1), 

### Question 4 : Comment on the obtained list.

In [10]:
print("Analysis of the Markov Chain:")
counts = {0: markov_chain.count(0), 1: markov_chain.count(1), 2: markov_chain.count(2)}
for state, count in counts.items():
    print(f"State {state}: {count} occurrences")

# Visualization
plt.bar(counts.keys(), counts.values(), tick_label=["Rock", "Paper", "Scissors"])
plt.title("State Distribution in the Generated Markov Chain")
plt.xlabel("States")
plt.ylabel("Frequency")
plt.show()

Analysis of the Markov Chain:
State 0: 27 occurrences
State 1: 10 occurrences
State 2: 63 occurrences


### Game implementation

### Question 7 : Analyse and fill out the code below to set a uniform random strategy for the computer. What does the graph represent? (Run the four following cell to launch the game interface).

In [11]:
#Rule of the game
dico=["Pierre","Feuille","Ciseaux"]
rule=np.array([[0,-1,1],[1,0,-1],[-1,1,0]]) #1 for a winning move, -1 for losing 
# and 0 for equality




In [12]:
#Initialisation
humanMoves=[]
victories=[]
Score=0
ScoreList=[]

In [21]:
import random
x = random.randint(0,2)
x

0

In [23]:
#game program
def play(a):
    #Machine decision making
    machineMove= random.randint(0,2) # à compléter à la question 7
    
    #Human move save
    humanMoves.append(a)
    
    #Save result
    victories.append(rule[humanMoves[-1],machineMove])
    
    #Total score of human
    Score=sum(victories)
    ScoreList.append(Score)
    
    #Plotting
    message1="Human :",dico[humanMoves[-1]],"Machine :",dico[machineMove],"gain for human :",rule[humanMoves[-1],machineMove]
    
    message2="Total score for human :",Score
    
    return (message1,message2,victories,Score,ScoreList)

In [25]:

#Man-Machine Interface
fenetre=Tk()
fenetre.title("your turn to play")
fenetre.minsize(width=600,height=600)
formulaire=Canvas(fenetre)
formulaire.pack()

label1=Label(formulaire)
label1.grid(row=3,column=1)

label2=Label(formulaire)
label2.grid(row=4,column=1)


def plotRock():
    Mes1,Mes2,Vict,score,scorelist=play(0)
    label1.config(text=Mes1)
    label2.config(text=Mes2)
    nb_parties=len(scorelist)
    plt.plot(scorelist)
    plt.xlim(0,nb_parties)
    plt.ylim(-nb_parties,nb_parties)
    plt.xlabel("number of games")
    plt.ylabel("Your score")
    plt.title("History")
    plt.show()
    
      
def plotPaper():
    Mes1,Mes2,Vict,score,scorelist=play(1)
    label1.config(text=Mes1)
    label2.config(text=Mes2)
    nb_parties=len(scorelist)
    plt.plot(scorelist)
    plt.xlim(0,nb_parties)
    plt.ylim(-nb_parties,nb_parties)
    plt.xlabel("number of games")
    plt.ylabel("Your score")
    plt.title("History")
    plt.show()

def plotScissors():
    Mes1,Mes2,Vict,score,scorelist=play(2)
    label1.config(text=Mes1)
    label2.config(text=Mes2)
    nb_parties=len(scorelist)
    plt.plot(scorelist)
    plt.xlim(0,nb_parties)
    plt.ylim(-nb_parties,nb_parties)
    plt.xlabel("number of games")
    plt.ylabel("Your score")
    plt.title("History")
    plt.show()
        

Rock=Button(formulaire,text="Rock",command=plotRock)
Rock.grid(row=0,column=0)

Paper=Button(formulaire,text="Paper",command=plotPaper)
Paper.grid(row=0,column=1)

Scissors=Button(formulaire,text="Scissors",command=plotScissors)
Scissors.grid(row=0,column=2)


    

mainloop()

KeyboardInterrupt: 

### Question 8 : Copy paste the four previous cells et rename the function "play(a)" into "play2(a)". Initialize a $3\times 3$ matrix "Mem" in part #Initialisation. Fill out #Save result to modify Mem so that "Mem$[i,j]$" is the number $n_{i,j}$. Explicitely plot Mem in the Man-Machine Interface.

In [26]:
#Rule of the game
dico=["Pierre","Feuille","Ciseaux"]
rule=np.array([[0,-1,1],[1,0,-1],[-1,1,0]]) #1 for a winning move, -1 for losing 
# and 0 for equality

#Initialisation
humanMoves=[]
victories=[]
Score=0
ScoreList=[]

Mem = np.zeros((3, 3), dtype=int)


def play2(a):
    # Machine decision making using AI
    if len(humanMoves) > 1:
        last_human_move = humanMoves[-1]
        machineMove = np.argmax([Mem[last_human_move, 2] - Mem[last_human_move, 1],
                                 Mem[last_human_move, 0] - Mem[last_human_move, 2],
                                 Mem[last_human_move, 1] - Mem[last_human_move, 0]])
    else:
        machineMove = random.randint(0, 2)  # Random choice for first moves

    # Human move save
    humanMoves.append(a)

    # Save result and update memory
    Mem[humanMoves[-2], a] += 1 if len(humanMoves) > 1 else 0
    victories.append(rule[humanMoves[-1], machineMove])

    # Total score of human
    Score = sum(victories)
    ScoreList.append(Score)

    # Plotting
    message1 = f"Human: {dico[humanMoves[-1]]}, Machine: {dico[machineMove]}, Gain for human: {rule[humanMoves[-1], machineMove]}"
    message2 = f"Total score for human: {Score}"

    return message1, message2, victories, Score, ScoreList





In [27]:

def showMem():
    print("Dynamic Memory Matrix:")
    print(Mem)


In [28]:
showMem()

Dynamic Memory Matrix:
[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [ ]:

#Man-Machine Interface
fenetre=Tk()
fenetre.title("your turn to play")
fenetre.minsize(width=600,height=600)
formulaire=Canvas(fenetre)
formulaire.pack()

label1=Label(formulaire)
label1.grid(row=3,column=1)

label2=Label(formulaire)
label2.grid(row=4,column=1)


def plotRock():
    Mes1,Mes2,Vict,score,scorelist=play2(0)
    label1.config(text=Mes1)
    label2.config(text=Mes2)
    nb_parties=len(scorelist)
    plt.plot(scorelist)
    plt.xlim(0,nb_parties)
    plt.ylim(-nb_parties,nb_parties)
    plt.xlabel("number of games")
    plt.ylabel("Your score")
    plt.title("History")
    plt.show()
    
      
def plotPaper():
    Mes1,Mes2,Vict,score,scorelist=play2(1)
    label1.config(text=Mes1)
    label2.config(text=Mes2)
    nb_parties=len(scorelist)
    plt.plot(scorelist)
    plt.xlim(0,nb_parties)
    plt.ylim(-nb_parties,nb_parties)
    plt.xlabel("number of games")
    plt.ylabel("Your score")
    plt.title("History")
    plt.show()

def plotScissors():
    Mes1,Mes2,Vict,score,scorelist=play2(2)
    label1.config(text=Mes1)
    label2.config(text=Mes2)
    nb_parties=len(scorelist)
    plt.plot(scorelist)
    plt.xlim(0,nb_parties)
    plt.ylim(-nb_parties,nb_parties)
    plt.xlabel("number of games")
    plt.ylabel("Your score")
    plt.title("History")
    plt.show()
        

Rock=Button(formulaire,text="Rock",command=plotRock)
Rock.grid(row=0,column=0)

Paper=Button(formulaire,text="Paper",command=plotPaper)
Paper.grid(row=0,column=1)

Scissors=Button(formulaire,text="Scissors",command=plotScissors)
Scissors.grid(row=0,column=2)


    

mainloop()

In [ ]:
#Function giving the number (i,j) in a list b of size >2
def nij(b,i,j):
    

### Question 9 : Similarily to question 8, copy paste and rename as "play3(a)". In part #Decision making, implement the artificial intelligence with the presented method. Comment on the results.

###  Statistical tests

### Question 10 : Create a list "listRandom" of size $100$ that you will fill by hand with values $1$ or $-1$, trying to approximately respect a uniform distribution. Create a list "listMachine" of same size with values $-1$ ou $1$ using "np.random.choice". 

### Question 11 : Compute $I(0)$. What information is given by $I(p)$ for $p>0$? What is the value of $I(p)$ when $X_k$ are iid variables on $\{-1,1\}$?

### Question 12 : Create a function "autocorr(X,p)" with input a list $X$ of $100$ integers, un entier $p\in \{0,\ldots,99\}$ and returns the autocorrelation of $X$ in $p$.

In [ ]:
def autocorr(X,p):
    

### Question 13 : Plot the autocorrelation of the two lists in function of $p$. Comment.

### Question 14 : Create a sample "ech" of size $5000$ of the random variable $I(1)$. 

### Question 15 : Plot "ech" with a histogram. Compute the empirical mean and variance of "ech". Deduce an approximate law of $I(1)$.

### Question 16 : Formulate the bilateral statistical test: null and alternative hypothesis, test statistic, critical values. Conclude.

### Rock-Paper-Scissors-Lizard-Spock